gene:
  # Configurazione segnali
  signals:
    batch_size: 5  # Dimensione batch per processing geni
    retry:
      max_attempts: 5
      initial_delay: 0.1
      max_delay: 2.0

  base:
    mutation_rate: 0.1
    crossover_rate: 0.7
    weight: 1.0
    risk_factor: 0.5
    test_period_days: 30
  
  rsi:
    default:
      period: 14
      overbought: 75  # Aumentato per segnali più conservativi
      oversold: 25    # Diminuito per segnali più conservativi
      weight: 1.0
      risk_factor: 0.5
    constraints:
      period:
        min: 2
        max: 50
      overbought:
        min: 50
        max: 100
      oversold:
        min: 0
        max: 50
      weight:
        min: 0.1
        max: 5.0
      risk_factor:
        min: 0.1
        max: 1.0
  
  moving_average:
    default:
      period: 20
      type: "SMA"
      distance: 0.03  # Aumentato per segnali più significativi
      weight: 1.0
      risk_factor: 0.4
    constraints:
      period:
        min: 5
        max: 200
      type:
        types: ["SMA", "EMA"]
      distance:
        min: 0.01
        max: 0.1
      weight:
        min: 0.1
        max: 5.0
      risk_factor:
        min: 0.1
        max: 1.0
  
  macd:
    default:
      fast_period: 8    # Ridotto per maggiore reattività
      slow_period: 21   # Ridotto per maggiore reattività
      signal_period: 5  # Ridotto per maggiore reattività
      weight: 1.0
      risk_factor: 0.6
    constraints:
      fast_period:
        min: 2
        max: 50
      slow_period:
        min: 5
        max: 100
      signal_period:
        min: 2
        max: 50
      weight:
        min: 0.1
        max: 5.0
      risk_factor:
        min: 0.1
        max: 1.0
  
  bollinger:
    default:
      period: 20
      std_dev: 2.5    # Aumentato per segnali più conservativi
      weight: 1.0
      risk_factor: 0.7
    constraints:
      period:
        min: 5
        max: 50
      std_dev:
        min: 1
        max: 4
      weight:
        min: 0.1
        max: 5.0
      risk_factor:
        min: 0.1
        max: 1.0
  
  stochastic:
    default:
      k_period: 14
      d_period: 3
      smooth_k: 3
      overbought: 80
      oversold: 20
      weight: 1.0
      risk_factor: 0.5
    constraints:
      k_period:
        min: 5
        max: 50
      d_period:
        min: 2
        max: 10
      smooth_k:
        min: 1
        max: 10
      overbought:
        min: 50
        max: 100
      oversold:
        min: 0
        max: 50
      weight:
        min: 0.1
        max: 5.0
      risk_factor:
        min: 0.1
        max: 1.0
  
  atr:
    default:
      period: 14
      multiplier: 2.0
      weight: 1.0
      risk_factor: 0.8
    constraints:
      period:
        min: 5
        max: 50
      multiplier:
        min: 0.5
        max: 5.0
      weight:
        min: 0.1
        max: 5.0
      risk_factor:
        min: 0.1
        max: 1.0

  volume:
    default:
      period: 20
      threshold: 2.0
      min_price_change: 0.005
      weight: 1.0
      risk_factor: 0.6
    constraints:
      period:
        min: 5
        max: 50
      threshold:
        min: 1.1
        max: 5.0
      min_price_change:
        min: 0.001
        max: 0.05
      weight:
        min: 0.1
        max: 5.0
      risk_factor:
        min: 0.1
        max: 1.0
