gene:
  base:
    crossover_rate: 0.7
    mutation_rate: 0.1
    test_period_days: 30
    weight: 1.0
  bollinger:
    constraints:
      period:
        max: 50
        min: 5
      std_dev:
        max: 4
        min: 1
      touch_percentage:
        max: 1.0
        min: 0.1
    default:
      period: 20
      std_dev: 2
      touch_percentage: 0.5
  macd:
    constraints:
      fast_period:
        max: 50
        min: 5
      slow_period:
        max: 100
        min: 10
      signal_period:
        max: 30
        min: 3
      divergence:
        max: 0.1
        min: 0.01
    default:
      fast_period: 12
      slow_period: 26
      signal_period: 9
      divergence: 0.02
  moving_average:
    constraints:
      distance:
        max: 0.1
        min: 0.01
      period:
        max: 200
        min: 5
      type:
        types:
        - SMA
        - EMA
    default:
      distance: 0.02
      period: 20
      type: SMA
  rsi:
    constraints:
      overbought:
        max: 90
        min: 50
      oversold:
        max: 50
        min: 10
      period:
        max: 50
        min: 2
    default:
      overbought: 50
      oversold: 10
      period: 10
  stochastic:
    constraints:
      k_period:
        max: 50
        min: 5
      d_period:
        max: 20
        min: 3
      overbought:
        max: 90
        min: 60
      oversold:
        max: 40
        min: 10
    default:
      k_period: 14
      d_period: 3
      overbought: 80
      oversold: 20
  atr:
    constraints:
      period:
        max: 50
        min: 5
      multiplier:
        max: 3.0
        min: 0.5
    default:
      period: 14
      multiplier: 1.0
  volume:
    constraints:
      period:
        max: 50
        min: 5
      threshold:
        max: 3.0
        min: 1.2
      min_price_change:
        max: 0.05
        min: 0.001
    default:
      period: 20
      threshold: 1.5
      min_price_change: 0.005
  obv:
    constraints:
      period:
        max: 50
        min: 5
      threshold:
        max: 0.1
        min: 0.01
    default:
      period: 20
      threshold: 0.03
  volatility_breakout:
    constraints:
      period:
        max: 50
        min: 5
      multiplier:
        max: 3.0
        min: 0.5
      breakout_threshold:
        max: 0.05
        min: 0.001
      consolidation_periods:
        max: 20
        min: 3
    default:
      period: 20
      multiplier: 1.5
      breakout_threshold: 0.01
      consolidation_periods: 5
  candlestick:
    constraints:
      doji_threshold:
        max: 0.3
        min: 0.05
      shadow_ratio:
        max: 0.5
        min: 0.1
      engulfing_size:
        max: 2.0
        min: 1.1
      star_body_size:
        max: 0.3
        min: 0.05
      harami_size:
        max: 0.8
        min: 0.2
      pattern_weight:
        max: 1.0
        min: 0.1
    default:
      doji_threshold: 0.1
      shadow_ratio: 0.3
      engulfing_size: 1.5
      star_body_size: 0.15
      harami_size: 0.5
      pattern_weight: 0.5
