gene:
  base:
    mutation_rate: 0.1
    crossover_rate: 0.7
    weight: 1.0
    test_period_days: 30
  
  rsi:
    default:
      period: 14
      overbought: 70
      oversold: 30
      weight: 1.0
    constraints:
      period:
        min: 2
        max: 50
      overbought:
        min: 50
        max: 100
      oversold:
        min: 0
        max: 50
      weight:
        min: 0.1
        max: 5.0
  
  moving_average:
    default:
      short_period: 9
      long_period: 21
      weight: 1.0
    constraints:
      short_period:
        min: 2
        max: 50
      long_period:
        min: 5
        max: 200
      weight:
        min: 0.1
        max: 5.0
  
  macd:
    default:
      fast_period: 12
      slow_period: 26
      signal_period: 9
      weight: 1.0
    constraints:
      fast_period:
        min: 2
        max: 50
      slow_period:
        min: 5
        max: 100
      signal_period:
        min: 2
        max: 50
      weight:
        min: 0.1
        max: 5.0
  
  bollinger:
    default:
      period: 20
      std_dev: 2
      weight: 1.0
    constraints:
      period:
        min: 5
        max: 50
      std_dev:
        min: 1
        max: 4
      weight:
        min: 0.1
        max: 5.0
  
  stochastic:
    default:
      k_period: 14
      d_period: 3
      smooth_k: 3
      overbought: 80
      oversold: 20
      weight: 1.0
    constraints:
      k_period:
        min: 5
        max: 50
      d_period:
        min: 2
        max: 10
      smooth_k:
        min: 1
        max: 10
      overbought:
        min: 50
        max: 100
      oversold:
        min: 0
        max: 50
      weight:
        min: 0.1
        max: 5.0
  
  atr:
    default:
      period: 14
      multiplier: 2.0
      weight: 1.0
    constraints:
      period:
        min: 5
        max: 50
      multiplier:
        min: 0.5
        max: 5.0
      weight:
        min: 0.1
        max: 5.0
