version: 1
disable_existing_loggers: false

system:
  data_dir: data
  indicators:
    cache_size: 1000
    enabled: true
  log_format: colored
  log_level: DEBUG
  download:
    batch_size:
      "1m": 1000
      "5m": 1000
      "15m": 1000
      "1h": 1000
      "4h": 1000
      "1d": 1000

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  colored:
    (): cli.logger.formatters.ColoredFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  test:
    format: '%(asctime)s - TEST - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: logs/tradingdna.log
    encoding: utf8

  test_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: test
    filename: logs/test.log
    encoding: utf8

loggers:
  # Gene System
  gene_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  gene_manager_analytics:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  gene_manager_base:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  # Population System
  population_base:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  population_creator:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  population_monitor:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  population_menu:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  # Evolution System
  evolution_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  selection_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  reproduction_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  mutation_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  fitness_calculator:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  evolution_test:
    level: DEBUG
    handlers: [console, test_file]
    propagate: no

  evolution_tests:
    level: DEBUG
    handlers: [console, test_file]
    propagate: no

  test_population_creator:
    level: DEBUG
    handlers: [console, test_file]
    propagate: no

  test_db_initializer:
    level: DEBUG
    handlers: [console, test_file]
    propagate: no

  # Data System
  data_downloader:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  data_processor:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  data_synchronizer:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  data_validator:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  # Database System
  database_models:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  query_optimizer:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  cache_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  # CLI System
  menu_core:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  menu_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  menu_utils:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  download_manager:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  # Progress System
  progress_indicators:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  progress_formatters:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  # Config System
  config_loader:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  config_validators:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  # Connector System
  base_connector:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  ccxt_connector:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  rate_limiter:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  retry_handler:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file]
