# Configurazione popolazione trading

# Limiti dimensione popolazione
population_size:
  min: 50
  max: 500

# Parametri evolutivi
evolution:
  mutation_rate:
    min: 0.001  # 0.1%
    max: 0.05   # 5%
    default: 0.01
  selection_pressure:
    min: 1
    max: 10
    default: 5
  generation_interval:
    min: 1  # ore
    max: 24
    default: 4
  diversity_threshold:
    min: 0.5
    max: 1.0
    default: 0.7
    
  # Parametri fitness
  fitness:
    weights:
      total_return: 0.3
      win_rate: 0.2
      sharpe_ratio: 0.2
      max_drawdown: -0.3
      
  # Parametri validazione
  validation:
    min_improvement: 0.05  # 5% miglioramento minimo
    min_win_rate: 0.45    # 45% win rate minimo
    max_drawdown: 0.20    # 20% drawdown massimo
    min_trades: 10        # Minimo numero trade

# Stati popolazione
status:
  values:
    - active
    - paused 
    - archived
  default: active

# Metriche popolazione
metrics:
  diversity_score:
    min: 0.0
    max: 1.0
    default: 1.0
  performance_score:
    min: 0.0
    max: 100.0
    default: 0.0

# Formati visualizzazione
display:
  date_format: "%Y-%m-%d %H:%M:%S"
  table_columns:
    - ID
    - Nome
    - Generazione
    - Dimensione
    - Status
    - Performance
    - Diversità
    - Asset
    - Timeframe
    - Creazione
