portfolio:
  mode: backtest
  symbols:
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  timeframes:
  - 1h
  - 4h
  - 1d
  risk_management:
    signal_threshold: 0.35  # Aumentato per avere segnali più affidabili
    stop_loss_pct: 0.015   # Ridotto per migliorare risk/reward
    take_profit_pct: 0.045 # Aumentato per migliorare risk/reward
    max_position_size: 0.1
    trailing_stop_pct: 0.015 # Aumentato per proteggere meglio i profitti
    initial_capital: 1000.0
    commission: 0.001
    slippage: 0.001
