security:
  backup_interval: 86400
  enable_backup: true

database:
  # Configurazione connessione PostgreSQL
  url: "postgresql://postgres:ninja@localhost:5432/tradingdna"
  
  # Configurazione del pool di connessioni
  pool_size: 20
  max_overflow: 30
  pool_timeout: 60
  pool_recycle: 3600
  pool_pre_ping: true
  
  # Configurazione comportamento database
  echo: false
  isolation_level: "READ COMMITTED"
  
  # Parametri di connessione PostgreSQL
  connect_args:
    application_name: "TradingDNA"
    client_encoding: "utf8"
    options: "-c timezone=UTC"
  
  # Configurazione runtime PostgreSQL
  runtime_params:
    statement_timeout: 60000
    lock_timeout: 10000
    idle_in_transaction_session_timeout: 600000
