system:
  data_dir: data
  indicators:
    cache_size: 1000
    enabled: true
  log_format: colored
  log_level: ERROR
  download:
    batch_size:
      "1m": 1000
      "5m": 1000
      "15m": 1000
      "1h": 1000
      "4h": 1000
      "1d": 1000
